services:
  - type: web
    name: weedify-bot
    env: node
    buildCommand: "./render-build.sh"
    startCommand: "node main.js"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GENIUS_API_KEY
        sync: false
