services:
  - type: web
    name: weedify-bot
    env: docker
    plan: free
    envVars:
      - key: TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GENIUS_API_KEY
        sync: false
